# PostgreSQL - values come from Render environment variables
spring.datasource.url=postgresql://rootdb_9rcb_user:K3SoiLSO820jQYLAnrss17fli6LOuUIL@dpg-d8c2fg57vvec73b77mq0-a/rootdb_9rcb
spring.datasource.username=rootdb_9rcb_user
spring.datasource.password=K3SoiLSO820jQYLAnrss17fli6LOuUIL
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false